import type { DemoPlace } from './types'

export const DEMO_PLACES: DemoPlace[] = [
  {
    id: 'fushimi-inari',
    name: '伏見稲荷大社',
    address: '京都府京都市伏見区深草薮之内町68',
    lat: 34.9671,
    lng: 135.7727,
    photos: [
      { id: 'p1', baseUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Fushimi_Inari-taisha_1.jpg/640px-Fushimi_Inari-taisha_1.jpg', filename: 'fushimi1.jpg', creationTime: '2024-03-15T10:00:00Z', mimeType: 'image/jpeg' },
    ],
    firstVisit: '2024-03-15',
    lastVisit: '2024-03-15',
    visitCount: 1,
    knowledgeScore: 0,
    quizCompleted: false,
    category: 'shrine_temple',
    country: '日本',
    prefecture: '京都府',
    description: '約1万本の朱塗りの鳥居で有名な稲荷神社の総本社。',
    funFacts: ['創建は711年（和銅4年）', '鳥居の総数は約1万本', '外国人に最も人気の観光スポット'],
  },
  {
    id: 'arashiyama',
    name: '嵐山竹林',
    address: '京都府京都市右京区嵯峨野宮之東町',
    lat: 35.0094,
    lng: 135.6721,
    photos: [
      { id: 'p2', baseUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Bamboo_Forest_Arashiyama_%28cropped%29.JPG/640px-Bamboo_Forest_Arashiyama_%28cropped%29.JPG', filename: 'arashiyama.jpg', creationTime: '2024-03-16T09:00:00Z', mimeType: 'image/jpeg' },
    ],
    firstVisit: '2024-03-16',
    lastVisit: '2024-03-16',
    visitCount: 1,
    knowledgeScore: 45,
    quizCompleted: true,
    category: 'nature',
    country: '日本',
    prefecture: '京都府',
    description: '高さ20mを超える孟宗竹が並ぶ幻想的な竹の道。',
    funFacts: ['竹の高さは最大で約20m', '気温が周囲より2〜3°C低い', '映画・CM撮影地として人気'],
  },
  {
    id: 'senso-ji',
    name: '浅草寺',
    address: '東京都台東区浅草2丁目3-1',
    lat: 35.7148,
    lng: 139.7967,
    photos: [
      { id: 'p3', baseUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Sensoji_Asakusa_Ushi3.jpg/640px-Sensoji_Asakusa_Ushi3.jpg', filename: 'sensoji.jpg', creationTime: '2024-01-05T11:00:00Z', mimeType: 'image/jpeg' },
    ],
    firstVisit: '2024-01-05',
    lastVisit: '2024-11-23',
    visitCount: 3,
    knowledgeScore: 72,
    quizCompleted: true,
    category: 'shrine_temple',
    country: '日本',
    prefecture: '東京都',
    description: '東京最古の寺院で、年間約3000万人が訪れる観光名所。',
    funFacts: ['創建は628年', '雷門の大提灯は重さ約700kg', '年間参拝者数は日本最多'],
  },
  {
    id: 'fuji',
    name: '富士山',
    address: '山梨県・静岡県',
    lat: 35.3607,
    lng: 138.7274,
    photos: [
      { id: 'p4', baseUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/080103_hakkai_fuji.jpg/640px-080103_hakkai_fuji.jpg', filename: 'fuji.jpg', creationTime: '2023-08-12T05:00:00Z', mimeType: 'image/jpeg' },
    ],
    firstVisit: '2023-08-12',
    lastVisit: '2023-08-12',
    visitCount: 1,
    knowledgeScore: 88,
    quizCompleted: true,
    category: 'mountain',
    country: '日本',
    prefecture: '山梨県・静岡県',
    description: '標高3776mの日本最高峰。2013年にユネスコ世界文化遺産に登録。',
    funFacts: ['標高3776.24m（日本最高峰）', '最後の噴火は1707年の宝永大噴火', '2013年に世界文化遺産登録'],
  },
  {
    id: 'dotonbori',
    name: '道頓堀',
    address: '大阪府大阪市中央区道頓堀',
    lat: 34.6687,
    lng: 135.5013,
    photos: [
      { id: 'p5', baseUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Dotonbori_at_night_%282%29.jpg/640px-Dotonbori_at_night_%282%29.jpg', filename: 'dotonbori.jpg', creationTime: '2024-07-20T19:00:00Z', mimeType: 'image/jpeg' },
    ],
    firstVisit: '2024-07-20',
    lastVisit: '2024-07-21',
    visitCount: 2,
    knowledgeScore: 30,
    quizCompleted: false,
    category: 'food',
    country: '日本',
    prefecture: '大阪府',
    description: '大阪を代表するグルメ・エンターテインメントエリア。',
    funFacts: ['1615年に道頓堀川が開削された', 'グリコの看板は1935年から', '「くいだおれ太郎」は大阪食文化の象徴'],
  },
  {
    id: 'hiroshima-peace',
    name: '広島平和記念公園',
    address: '広島県広島市中区中島町1-2',
    lat: 34.3955,
    lng: 132.4533,
    photos: [
      { id: 'p6', baseUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Hiroshima_Peace_Memorial_Museum_%26_A-bomb_Dome.jpg/640px-Hiroshima_Peace_Memorial_Museum_%26_A-bomb_Dome.jpg', filename: 'hiroshima.jpg', creationTime: '2023-11-03T10:00:00Z', mimeType: 'image/jpeg' },
    ],
    firstVisit: '2023-11-03',
    lastVisit: '2023-11-03',
    visitCount: 1,
    knowledgeScore: 0,
    quizCompleted: false,
    category: 'museum',
    country: '日本',
    prefecture: '広島県',
    description: '1945年の原爆投下地に建てられた世界平和の祈念公園。',
    funFacts: ['原爆投下は1945年8月6日午前8時15分', '原爆ドームは1996年に世界遺産登録', '公園内には50000本の木が植えられている'],
  },
  {
    id: 'naha-shurijo',
    name: '首里城',
    address: '沖縄県那覇市首里金城町1-2',
    lat: 26.2172,
    lng: 127.7190,
    photos: [
      { id: 'p7', baseUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Shuri_Castle_1.jpg/640px-Shuri_Castle_1.jpg', filename: 'shurijo.jpg', creationTime: '2024-05-10T13:00:00Z', mimeType: 'image/jpeg' },
    ],
    firstVisit: '2024-05-10',
    lastVisit: '2024-05-10',
    visitCount: 1,
    knowledgeScore: 15,
    quizCompleted: false,
    category: 'museum',
    country: '日本',
    prefecture: '沖縄県',
    description: '琉球王国の王宮として約450年にわたり使われた世界遺産の城。',
    funFacts: ['1429年から約450年間、琉球王国の王宮だった', '2000年にユネスコ世界遺産登録', '2019年10月の火災後、復元工事中'],
  },
  {
    id: 'nikko-toshogu',
    name: '日光東照宮',
    address: '栃木県日光市山内2301',
    lat: 36.7581,
    lng: 139.5989,
    photos: [
      { id: 'p8', baseUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Nikko_tosho-gu_2007_April.jpg/640px-Nikko_tosho-gu_2007_April.jpg', filename: 'nikko.jpg', creationTime: '2023-10-28T10:00:00Z', mimeType: 'image/jpeg' },
    ],
    firstVisit: '2023-10-28',
    lastVisit: '2023-10-28',
    visitCount: 1,
    knowledgeScore: 55,
    quizCompleted: true,
    category: 'shrine_temple',
    country: '日本',
    prefecture: '栃木県',
    description: '江戸幕府初代将軍・徳川家康を祀る豪華絢爛な神社。',
    funFacts: ['1617年創建、江戸幕府2代将軍秀忠が建立', '「見ざる言わざる聞かざる」の三猿で有名', '1999年ユネスコ世界遺産登録'],
  },
]

export const DEMO_USER_STATS = {
  totalPlaces: DEMO_PLACES.length,
  totalPhotos: 12,
  totalXp: 1250,
  level: 3,
  badges: [
    { id: 'first-quiz', name: '初クイズクリア', description: '初めてクイズをクリアした', icon: '🎯', earnedAt: '2024-01-05' },
    { id: 'kyoto-lover', name: '京都好き', description: '京都の場所を2か所以上訪問', icon: '⛩️', earnedAt: '2024-03-16' },
    { id: 'mountain-climber', name: '登山家', description: '山のカテゴリを訪問', icon: '🗻', earnedAt: '2023-08-12' },
    { id: 'quiz-master', name: 'クイズマスター', description: 'クイズで90点以上を獲得', icon: '🏆', earnedAt: '2023-10-28' },
  ],
  quizzesTaken: 5,
  correctAnswers: 38,
}
