import type { ChineseWord, WordCategory } from './chinese-types'

export const HSK5_WORDS: ChineseWord[] = [
  // ── daily_life ─────────────────────────────────────────────────────────
  { id: 'w001', hanzi: '整理', pinyin: 'zhěng lǐ', meaning: 'to organize, tidy up', meaningJa: '整理する、片付ける', category: 'daily_life' },
  { id: 'w002', hanzi: '烦恼', pinyin: 'fán nǎo', meaning: 'worry, trouble, vexation', meaningJa: '悩み、煩い', category: 'daily_life' },
  { id: 'w003', hanzi: '效率', pinyin: 'xiào lǜ', meaning: 'efficiency', meaningJa: '効率', category: 'daily_life' },
  { id: 'w004', hanzi: '节省', pinyin: 'jié shěng', meaning: 'to economize, save', meaningJa: '節約する、倹約する', category: 'daily_life' },
  { id: 'w005', hanzi: '陪伴', pinyin: 'péi bàn', meaning: 'to accompany, keep company', meaningJa: '付き添う、一緒にいる', category: 'daily_life' },
  { id: 'w006', hanzi: '提前', pinyin: 'tí qián', meaning: 'in advance, ahead of schedule', meaningJa: '前もって、前倒しにする', category: 'daily_life' },
  { id: 'w007', hanzi: '准时', pinyin: 'zhǔn shí', meaning: 'on time, punctual', meaningJa: '時間通りに、定刻に', category: 'daily_life' },
  { id: 'w008', hanzi: '便利', pinyin: 'biàn lì', meaning: 'convenient', meaningJa: '便利な', category: 'daily_life' },
  { id: 'w009', hanzi: '耐心', pinyin: 'nài xīn', meaning: 'patient, patience', meaningJa: '辛抱強い、忍耐', category: 'daily_life' },
  { id: 'w010', hanzi: '打扰', pinyin: 'dǎ rǎo', meaning: 'to disturb, bother', meaningJa: '邪魔する、迷惑をかける', category: 'daily_life' },
  { id: 'w011', hanzi: '顺便', pinyin: 'shùn biàn', meaning: 'conveniently, in passing', meaningJa: 'ついでに', category: 'daily_life' },
  { id: 'w012', hanzi: '浪费', pinyin: 'làng fèi', meaning: 'to waste', meaningJa: '無駄遣いする、浪費する', category: 'daily_life' },
  { id: 'w013', hanzi: '坚持', pinyin: 'jiān chí', meaning: 'to persist, keep at', meaningJa: '続ける、持ちこたえる', category: 'daily_life' },
  { id: 'w014', hanzi: '积累', pinyin: 'jī lěi', meaning: 'to accumulate, build up', meaningJa: '積み重ねる、蓄積する', category: 'daily_life' },
  { id: 'w015', hanzi: '安排', pinyin: 'ān pái', meaning: 'to arrange, arrangement', meaningJa: '手配する、段取り', category: 'daily_life' },
  { id: 'w016', hanzi: '充实', pinyin: 'chōng shí', meaning: 'fulfilling, to enrich', meaningJa: '充実した、豊かにする', category: 'daily_life' },
  { id: 'w017', hanzi: '克服', pinyin: 'kè fú', meaning: 'to overcome', meaningJa: '克服する', category: 'daily_life' },
  { id: 'w018', hanzi: '适应', pinyin: 'shì yìng', meaning: 'to adapt, adjust to', meaningJa: '適応する、慣れる', category: 'daily_life' },
  { id: 'w019', hanzi: '维持', pinyin: 'wéi chí', meaning: 'to maintain, keep up', meaningJa: '維持する', category: 'daily_life' },
  { id: 'w020', hanzi: '调整', pinyin: 'tiáo zhěng', meaning: 'to adjust, regulate', meaningJa: '調整する', category: 'daily_life' },
  { id: 'w021', hanzi: '复杂', pinyin: 'fù zá', meaning: 'complex, complicated', meaningJa: '複雑な', category: 'daily_life' },
  { id: 'w022', hanzi: '细心', pinyin: 'xì xīn', meaning: 'careful, attentive', meaningJa: '細かい気配り、注意深い', category: 'daily_life' },
  { id: 'w023', hanzi: '粗心', pinyin: 'cū xīn', meaning: 'careless, inattentive', meaningJa: 'うっかりした、不注意な', category: 'daily_life' },
  { id: 'w024', hanzi: '操心', pinyin: 'cāo xīn', meaning: 'to worry about, take trouble', meaningJa: '心配する、苦労する', category: 'daily_life' },
  { id: 'w025', hanzi: '减少', pinyin: 'jiǎn shǎo', meaning: 'to reduce, decrease', meaningJa: '減らす、減少する', category: 'daily_life' },
  { id: 'w026', hanzi: '增加', pinyin: 'zēng jiā', meaning: 'to increase, add', meaningJa: '増やす、増加する', category: 'daily_life' },
  { id: 'w027', hanzi: '如何', pinyin: 'rú hé', meaning: 'how, in what way', meaningJa: 'いかに、どのように', category: 'daily_life' },
  { id: 'w028', hanzi: '依然', pinyin: 'yī rán', meaning: 'still, as before', meaningJa: 'まだ、依然として', category: 'daily_life' },
  { id: 'w029', hanzi: '逐渐', pinyin: 'zhú jiàn', meaning: 'gradually, step by step', meaningJa: '徐々に、だんだんと', category: 'daily_life' },
  { id: 'w030', hanzi: '习惯', pinyin: 'xí guàn', meaning: 'habit; to be used to', meaningJa: '習慣；慣れる', category: 'daily_life' },

  // ── work_business ──────────────────────────────────────────────────────
  { id: 'w031', hanzi: '合同', pinyin: 'hé tong', meaning: 'contract, agreement', meaningJa: '契約書、契約', category: 'work_business' },
  { id: 'w032', hanzi: '谈判', pinyin: 'tán pàn', meaning: 'to negotiate, negotiation', meaningJa: '交渉する、談判', category: 'work_business' },
  { id: 'w033', hanzi: '投资', pinyin: 'tóu zī', meaning: 'to invest, investment', meaningJa: '投資する、投資', category: 'work_business' },
  { id: 'w034', hanzi: '竞争', pinyin: 'jìng zhēng', meaning: 'to compete, competition', meaningJa: '競争する、競合', category: 'work_business' },
  { id: 'w035', hanzi: '企业', pinyin: 'qǐ yè', meaning: 'enterprise, company', meaningJa: '企業', category: 'work_business' },
  { id: 'w036', hanzi: '策略', pinyin: 'cè lüè', meaning: 'strategy, tactic', meaningJa: '戦略、策略', category: 'work_business' },
  { id: 'w037', hanzi: '利润', pinyin: 'lì rùn', meaning: 'profit', meaningJa: '利潤、利益', category: 'work_business' },
  { id: 'w038', hanzi: '市场', pinyin: 'shì chǎng', meaning: 'market', meaningJa: '市場', category: 'work_business' },
  { id: 'w039', hanzi: '汇报', pinyin: 'huì bào', meaning: 'to report, brief', meaningJa: '報告する', category: 'work_business' },
  { id: 'w040', hanzi: '签署', pinyin: 'qiān shǔ', meaning: 'to sign (a document)', meaningJa: '署名する、締結する', category: 'work_business' },
  { id: 'w041', hanzi: '方案', pinyin: 'fāng àn', meaning: 'plan, scheme, proposal', meaningJa: '方案、計画案', category: 'work_business' },
  { id: 'w042', hanzi: '预算', pinyin: 'yù suàn', meaning: 'budget', meaningJa: '予算', category: 'work_business' },
  { id: 'w043', hanzi: '成本', pinyin: 'chéng běn', meaning: 'cost', meaningJa: 'コスト、原価', category: 'work_business' },
  { id: 'w044', hanzi: '效益', pinyin: 'xiào yì', meaning: 'benefit, economic efficiency', meaningJa: '効益、費用対効果', category: 'work_business' },
  { id: 'w045', hanzi: '业绩', pinyin: 'yè jì', meaning: 'business performance, achievement', meaningJa: '業績', category: 'work_business' },
  { id: 'w046', hanzi: '项目', pinyin: 'xiàng mù', meaning: 'project, item', meaningJa: 'プロジェクト、項目', category: 'work_business' },
  { id: 'w047', hanzi: '实施', pinyin: 'shí shī', meaning: 'to implement, carry out', meaningJa: '実施する、施行する', category: 'work_business' },
  { id: 'w048', hanzi: '监督', pinyin: 'jiān dū', meaning: 'to supervise, oversee', meaningJa: '監督する', category: 'work_business' },
  { id: 'w049', hanzi: '评估', pinyin: 'píng gū', meaning: 'to evaluate, assess', meaningJa: '評価する、査定する', category: 'work_business' },
  { id: 'w050', hanzi: '资金', pinyin: 'zī jīn', meaning: 'funds, capital', meaningJa: '資金', category: 'work_business' },
  { id: 'w051', hanzi: '收益', pinyin: 'shōu yì', meaning: 'income, revenue, earnings', meaningJa: '収益', category: 'work_business' },
  { id: 'w052', hanzi: '损失', pinyin: 'sǔn shī', meaning: 'loss, damage', meaningJa: '損失', category: 'work_business' },
  { id: 'w053', hanzi: '股票', pinyin: 'gǔ piào', meaning: 'stock, shares', meaningJa: '株式', category: 'work_business' },
  { id: 'w054', hanzi: '汇率', pinyin: 'huì lǜ', meaning: 'exchange rate', meaningJa: '為替レート', category: 'work_business' },
  { id: 'w055', hanzi: '进展', pinyin: 'jìn zhǎn', meaning: 'progress, development', meaningJa: '進展、進捗', category: 'work_business' },
  { id: 'w056', hanzi: '合理', pinyin: 'hé lǐ', meaning: 'reasonable, rational', meaningJa: '合理的な、妥当な', category: 'work_business' },
  { id: 'w057', hanzi: '债务', pinyin: 'zhài wù', meaning: 'debt, liability', meaningJa: '債務', category: 'work_business' },

  // ── education ──────────────────────────────────────────────────────────
  { id: 'w058', hanzi: '培训', pinyin: 'péi xùn', meaning: 'training, to train', meaningJa: '研修、トレーニング', category: 'education' },
  { id: 'w059', hanzi: '学术', pinyin: 'xué shù', meaning: 'academic, scholarly', meaningJa: '学術、学問', category: 'education' },
  { id: 'w060', hanzi: '论文', pinyin: 'lùn wén', meaning: 'thesis, paper, essay', meaningJa: '論文', category: 'education' },
  { id: 'w061', hanzi: '实验', pinyin: 'shí yàn', meaning: 'experiment', meaningJa: '実験', category: 'education' },
  { id: 'w062', hanzi: '理论', pinyin: 'lǐ lùn', meaning: 'theory', meaningJa: '理論', category: 'education' },
  { id: 'w063', hanzi: '研究', pinyin: 'yán jiū', meaning: 'research, to study', meaningJa: '研究', category: 'education' },
  { id: 'w064', hanzi: '教材', pinyin: 'jiào cái', meaning: 'teaching materials, textbook', meaningJa: '教材', category: 'education' },
  { id: 'w065', hanzi: '奖学金', pinyin: 'jiǎng xué jīn', meaning: 'scholarship', meaningJa: '奨学金', category: 'education' },
  { id: 'w066', hanzi: '毕业', pinyin: 'bì yè', meaning: 'to graduate, graduation', meaningJa: '卒業する', category: 'education' },
  { id: 'w067', hanzi: '录取', pinyin: 'lù qǔ', meaning: 'to admit, enroll', meaningJa: '合格させる、採用する', category: 'education' },
  { id: 'w068', hanzi: '专业', pinyin: 'zhuān yè', meaning: 'major, specialty, professional', meaningJa: '専門、専攻', category: 'education' },
  { id: 'w069', hanzi: '课程', pinyin: 'kè chéng', meaning: 'curriculum, course', meaningJa: 'カリキュラム、授業', category: 'education' },
  { id: 'w070', hanzi: '成绩', pinyin: 'chéng jì', meaning: 'grades, academic results', meaningJa: '成績', category: 'education' },
  { id: 'w071', hanzi: '辩论', pinyin: 'biàn lùn', meaning: 'debate, to debate', meaningJa: '議論する、ディベート', category: 'education' },
  { id: 'w072', hanzi: '总结', pinyin: 'zǒng jié', meaning: 'summary, to summarize', meaningJa: 'まとめ、総括する', category: 'education' },
  { id: 'w073', hanzi: '翻译', pinyin: 'fān yì', meaning: 'translation, to translate', meaningJa: '翻訳する、通訳する', category: 'education' },
  { id: 'w074', hanzi: '分析', pinyin: 'fēn xī', meaning: 'analysis, to analyze', meaningJa: '分析する', category: 'education' },
  { id: 'w075', hanzi: '探讨', pinyin: 'tàn tǎo', meaning: 'to explore, discuss thoroughly', meaningJa: '探求する、探討する', category: 'education' },
  { id: 'w076', hanzi: '评价', pinyin: 'píng jià', meaning: 'evaluation, to evaluate', meaningJa: '評価する', category: 'education' },
  { id: 'w077', hanzi: '掌握', pinyin: 'zhǎng wò', meaning: 'to master, grasp', meaningJa: 'マスターする、把握する', category: 'education' },
  { id: 'w078', hanzi: '启发', pinyin: 'qǐ fā', meaning: 'to inspire, enlighten', meaningJa: '啓発する、ヒントを与える', category: 'education' },
  { id: 'w079', hanzi: '竞赛', pinyin: 'jìng sài', meaning: 'competition, contest', meaningJa: 'コンテスト、競技会', category: 'education' },
  { id: 'w080', hanzi: '写作', pinyin: 'xiě zuò', meaning: 'writing, composition', meaningJa: '文章を書くこと、作文', category: 'education' },
  { id: 'w081', hanzi: '考核', pinyin: 'kǎo hé', meaning: 'assessment, examination', meaningJa: '考査、評価審査', category: 'education' },

  // ── culture_art ────────────────────────────────────────────────────────
  { id: 'w082', hanzi: '传统', pinyin: 'chuán tǒng', meaning: 'tradition, traditional', meaningJa: '伝統、伝統的な', category: 'culture_art' },
  { id: 'w083', hanzi: '遗产', pinyin: 'yí chǎn', meaning: 'heritage, legacy', meaningJa: '遺産', category: 'culture_art' },
  { id: 'w084', hanzi: '民俗', pinyin: 'mín sú', meaning: 'folk customs, folklore', meaningJa: '民俗、風習', category: 'culture_art' },
  { id: 'w085', hanzi: '戏剧', pinyin: 'xì jù', meaning: 'drama, theater', meaningJa: '演劇、戯曲', category: 'culture_art' },
  { id: 'w086', hanzi: '欣赏', pinyin: 'xīn shǎng', meaning: 'to appreciate, enjoy', meaningJa: '鑑賞する、味わう', category: 'culture_art' },
  { id: 'w087', hanzi: '风格', pinyin: 'fēng gé', meaning: 'style, manner', meaningJa: 'スタイル、風格', category: 'culture_art' },
  { id: 'w088', hanzi: '展览', pinyin: 'zhǎn lǎn', meaning: 'exhibition, to exhibit', meaningJa: '展覧会、展示', category: 'culture_art' },
  { id: 'w089', hanzi: '作品', pinyin: 'zuò pǐn', meaning: 'work of art or literature', meaningJa: '作品', category: 'culture_art' },
  { id: 'w090', hanzi: '创作', pinyin: 'chuàng zuò', meaning: 'to create, creative work', meaningJa: '創作する、制作', category: 'culture_art' },
  { id: 'w091', hanzi: '历史', pinyin: 'lì shǐ', meaning: 'history', meaningJa: '歴史', category: 'culture_art' },
  { id: 'w092', hanzi: '文明', pinyin: 'wén míng', meaning: 'civilization, culture', meaningJa: '文明', category: 'culture_art' },
  { id: 'w093', hanzi: '古典', pinyin: 'gǔ diǎn', meaning: 'classical', meaningJa: '古典的な', category: 'culture_art' },
  { id: 'w094', hanzi: '现代', pinyin: 'xiàn dài', meaning: 'modern, contemporary', meaningJa: '現代の', category: 'culture_art' },
  { id: 'w095', hanzi: '美术', pinyin: 'měi shù', meaning: 'fine arts, visual art', meaningJa: '美術', category: 'culture_art' },
  { id: 'w096', hanzi: '雕塑', pinyin: 'diāo sù', meaning: 'sculpture', meaningJa: '彫刻', category: 'culture_art' },
  { id: 'w097', hanzi: '摄影', pinyin: 'shè yǐng', meaning: 'photography', meaningJa: '写真撮影', category: 'culture_art' },
  { id: 'w098', hanzi: '建筑', pinyin: 'jiàn zhù', meaning: 'architecture, building', meaningJa: '建築', category: 'culture_art' },
  { id: 'w099', hanzi: '绘画', pinyin: 'huì huà', meaning: 'painting, drawing', meaningJa: '絵画', category: 'culture_art' },
  { id: 'w100', hanzi: '诗歌', pinyin: 'shī gē', meaning: 'poetry, poem', meaningJa: '詩', category: 'culture_art' },
  { id: 'w101', hanzi: '小说', pinyin: 'xiǎo shuō', meaning: 'novel, fiction', meaningJa: '小説', category: 'culture_art' },
  { id: 'w102', hanzi: '文学', pinyin: 'wén xué', meaning: 'literature', meaningJa: '文学', category: 'culture_art' },
  { id: 'w103', hanzi: '表演', pinyin: 'biǎo yǎn', meaning: 'performance, to perform', meaningJa: '演じる、パフォーマンス', category: 'culture_art' },
  { id: 'w104', hanzi: '设计', pinyin: 'shè jì', meaning: 'design, to design', meaningJa: 'デザイン', category: 'culture_art' },
  { id: 'w105', hanzi: '风景', pinyin: 'fēng jǐng', meaning: 'scenery, landscape', meaningJa: '風景', category: 'culture_art' },

  // ── society_politics ───────────────────────────────────────────────────
  { id: 'w106', hanzi: '政策', pinyin: 'zhèng cè', meaning: 'policy', meaningJa: '政策', category: 'society_politics' },
  { id: 'w107', hanzi: '法律', pinyin: 'fǎ lǜ', meaning: 'law, legal', meaningJa: '法律', category: 'society_politics' },
  { id: 'w108', hanzi: '权利', pinyin: 'quán lì', meaning: 'right, entitlement', meaningJa: '権利', category: 'society_politics' },
  { id: 'w109', hanzi: '责任', pinyin: 'zé rèn', meaning: 'responsibility, duty', meaningJa: '責任', category: 'society_politics' },
  { id: 'w110', hanzi: '公平', pinyin: 'gōng píng', meaning: 'fair, just, impartial', meaningJa: '公平な、公正', category: 'society_politics' },
  { id: 'w111', hanzi: '改革', pinyin: 'gǎi gé', meaning: 'to reform, reform', meaningJa: '改革する', category: 'society_politics' },
  { id: 'w112', hanzi: '制度', pinyin: 'zhì dù', meaning: 'system, institution', meaningJa: '制度', category: 'society_politics' },
  { id: 'w113', hanzi: '民主', pinyin: 'mín zhǔ', meaning: 'democracy, democratic', meaningJa: '民主主義', category: 'society_politics' },
  { id: 'w114', hanzi: '公民', pinyin: 'gōng mín', meaning: 'citizen', meaningJa: '市民、公民', category: 'society_politics' },
  { id: 'w115', hanzi: '权力', pinyin: 'quán lì', meaning: 'power, authority', meaningJa: '権力', category: 'society_politics' },
  { id: 'w116', hanzi: '义务', pinyin: 'yì wù', meaning: 'obligation, duty', meaningJa: '義務', category: 'society_politics' },
  { id: 'w117', hanzi: '道德', pinyin: 'dào dé', meaning: 'morality, ethics', meaningJa: '道徳', category: 'society_politics' },
  { id: 'w118', hanzi: '社区', pinyin: 'shè qū', meaning: 'community', meaningJa: 'コミュニティ、地域', category: 'society_politics' },
  { id: 'w119', hanzi: '组织', pinyin: 'zǔ zhī', meaning: 'organization; to organize', meaningJa: '組織する', category: 'society_politics' },
  { id: 'w120', hanzi: '宣传', pinyin: 'xuān chuán', meaning: 'publicity, propaganda', meaningJa: '宣伝する', category: 'society_politics' },
  { id: 'w121', hanzi: '平等', pinyin: 'píng děng', meaning: 'equality, equal', meaningJa: '平等', category: 'society_politics' },
  { id: 'w122', hanzi: '自由', pinyin: 'zì yóu', meaning: 'freedom, liberty', meaningJa: '自由', category: 'society_politics' },
  { id: 'w123', hanzi: '和平', pinyin: 'hé píng', meaning: 'peace', meaningJa: '平和', category: 'society_politics' },
  { id: 'w124', hanzi: '冲突', pinyin: 'chōng tū', meaning: 'conflict, clash', meaningJa: '衝突', category: 'society_politics' },
  { id: 'w125', hanzi: '调查', pinyin: 'diào chá', meaning: 'investigation, survey', meaningJa: '調査する', category: 'society_politics' },
  { id: 'w126', hanzi: '统计', pinyin: 'tǒng jì', meaning: 'statistics', meaningJa: '統計', category: 'society_politics' },
  { id: 'w127', hanzi: '人口', pinyin: 'rén kǒu', meaning: 'population', meaningJa: '人口', category: 'society_politics' },
  { id: 'w128', hanzi: '经济', pinyin: 'jīng jì', meaning: 'economy', meaningJa: '経済', category: 'society_politics' },
  { id: 'w129', hanzi: '贫困', pinyin: 'pín kùn', meaning: 'poverty, impoverished', meaningJa: '貧困', category: 'society_politics' },
  { id: 'w130', hanzi: '福利', pinyin: 'fú lì', meaning: 'welfare, benefit', meaningJa: '福祉、福利厚生', category: 'society_politics' },
  { id: 'w131', hanzi: '保障', pinyin: 'bǎo zhàng', meaning: 'guarantee, security', meaningJa: '保障する', category: 'society_politics' },
  { id: 'w132', hanzi: '合法', pinyin: 'hé fǎ', meaning: 'legal, lawful', meaningJa: '合法的な', category: 'society_politics' },
  { id: 'w133', hanzi: '违法', pinyin: 'wéi fǎ', meaning: 'illegal, unlawful', meaningJa: '違法な', category: 'society_politics' },

  // ── health_body ────────────────────────────────────────────────────────
  { id: 'w134', hanzi: '治疗', pinyin: 'zhì liáo', meaning: 'to treat, treatment', meaningJa: '治療する', category: 'health_body' },
  { id: 'w135', hanzi: '症状', pinyin: 'zhèng zhuàng', meaning: 'symptom', meaningJa: '症状', category: 'health_body' },
  { id: 'w136', hanzi: '预防', pinyin: 'yù fáng', meaning: 'to prevent, prevention', meaningJa: '予防する', category: 'health_body' },
  { id: 'w137', hanzi: '营养', pinyin: 'yíng yǎng', meaning: 'nutrition, nourishment', meaningJa: '栄養', category: 'health_body' },
  { id: 'w138', hanzi: '心理', pinyin: 'xīn lǐ', meaning: 'psychology, mental state', meaningJa: '心理', category: 'health_body' },
  { id: 'w139', hanzi: '压力', pinyin: 'yā lì', meaning: 'pressure, stress', meaningJa: 'プレッシャー、ストレス', category: 'health_body' },
  { id: 'w140', hanzi: '恢复', pinyin: 'huī fù', meaning: 'to recover, restore', meaningJa: '回復する', category: 'health_body' },
  { id: 'w141', hanzi: '睡眠', pinyin: 'shuì mián', meaning: 'sleep', meaningJa: '睡眠', category: 'health_body' },
  { id: 'w142', hanzi: '体力', pinyin: 'tǐ lì', meaning: 'physical strength, stamina', meaningJa: '体力', category: 'health_body' },
  { id: 'w143', hanzi: '锻炼', pinyin: 'duàn liàn', meaning: 'exercise, to work out', meaningJa: '鍛える、運動する', category: 'health_body' },
  { id: 'w144', hanzi: '手术', pinyin: 'shǒu shù', meaning: 'surgery, operation', meaningJa: '手術', category: 'health_body' },
  { id: 'w145', hanzi: '药物', pinyin: 'yào wù', meaning: 'medicine, drug', meaningJa: '薬物、医薬品', category: 'health_body' },
  { id: 'w146', hanzi: '过敏', pinyin: 'guò mǐn', meaning: 'allergy, allergic', meaningJa: 'アレルギー', category: 'health_body' },
  { id: 'w147', hanzi: '疼痛', pinyin: 'téng tòng', meaning: 'pain, ache', meaningJa: '痛み', category: 'health_body' },
  { id: 'w148', hanzi: '疾病', pinyin: 'jí bìng', meaning: 'disease, illness', meaningJa: '疾病', category: 'health_body' },
  { id: 'w149', hanzi: '健身', pinyin: 'jiàn shēn', meaning: 'fitness, to work out', meaningJa: '健身、フィットネス', category: 'health_body' },
  { id: 'w150', hanzi: '减肥', pinyin: 'jiǎn féi', meaning: 'to lose weight, diet', meaningJa: 'ダイエットする', category: 'health_body' },
  { id: 'w151', hanzi: '消化', pinyin: 'xiāo huà', meaning: 'digestion, to digest', meaningJa: '消化する', category: 'health_body' },
  { id: 'w152', hanzi: '免疫', pinyin: 'miǎn yì', meaning: 'immunity', meaningJa: '免疫', category: 'health_body' },
  { id: 'w153', hanzi: '血压', pinyin: 'xuè yā', meaning: 'blood pressure', meaningJa: '血圧', category: 'health_body' },
  { id: 'w154', hanzi: '呼吸', pinyin: 'hū xī', meaning: 'breathing, to breathe', meaningJa: '呼吸する', category: 'health_body' },
  { id: 'w155', hanzi: '放松', pinyin: 'fàng sōng', meaning: 'to relax', meaningJa: 'リラックスする', category: 'health_body' },
  { id: 'w156', hanzi: '疲劳', pinyin: 'pí láo', meaning: 'fatigue, exhausted', meaningJa: '疲労', category: 'health_body' },
  { id: 'w157', hanzi: '保健', pinyin: 'bǎo jiàn', meaning: 'health care, wellness', meaningJa: '保健、健康管理', category: 'health_body' },

  // ── emotion_psychology ─────────────────────────────────────────────────
  { id: 'w158', hanzi: '失望', pinyin: 'shī wàng', meaning: 'disappointed, disappointment', meaningJa: 'がっかりする、失望', category: 'emotion_psychology' },
  { id: 'w159', hanzi: '激动', pinyin: 'jī dòng', meaning: 'excited, moved, emotional', meaningJa: '興奮する、感動する', category: 'emotion_psychology' },
  { id: 'w160', hanzi: '犹豫', pinyin: 'yóu yù', meaning: 'to hesitate, hesitant', meaningJa: '躊躇する、迷う', category: 'emotion_psychology' },
  { id: 'w161', hanzi: '自信', pinyin: 'zì xìn', meaning: 'confidence, self-confidence', meaningJa: '自信', category: 'emotion_psychology' },
  { id: 'w162', hanzi: '感激', pinyin: 'gǎn jī', meaning: 'grateful, thankful', meaningJa: '感謝する、感激する', category: 'emotion_psychology' },
  { id: 'w163', hanzi: '孤独', pinyin: 'gū dú', meaning: 'lonely, solitary', meaningJa: '孤独な', category: 'emotion_psychology' },
  { id: 'w164', hanzi: '骄傲', pinyin: 'jiāo ào', meaning: 'proud; arrogant', meaningJa: '誇りに思う；傲慢な', category: 'emotion_psychology' },
  { id: 'w165', hanzi: '委屈', pinyin: 'wěi qū', meaning: 'feel wronged, grievance', meaningJa: '不満を感じる、委屈', category: 'emotion_psychology' },
  { id: 'w166', hanzi: '后悔', pinyin: 'hòu huǐ', meaning: 'to regret', meaningJa: '後悔する', category: 'emotion_psychology' },
  { id: 'w167', hanzi: '满足', pinyin: 'mǎn zú', meaning: 'satisfied, to satisfy', meaningJa: '満足する', category: 'emotion_psychology' },
  { id: 'w168', hanzi: '兴奋', pinyin: 'xīng fèn', meaning: 'excited, excitement', meaningJa: '興奮した', category: 'emotion_psychology' },
  { id: 'w169', hanzi: '焦虑', pinyin: 'jiāo lǜ', meaning: 'anxiety, anxious', meaningJa: '不安、焦り', category: 'emotion_psychology' },
  { id: 'w170', hanzi: '抑郁', pinyin: 'yì yù', meaning: 'depression, depressed', meaningJa: 'うつ、憂鬱', category: 'emotion_psychology' },
  { id: 'w171', hanzi: '羡慕', pinyin: 'xiàn mù', meaning: 'to envy, admire', meaningJa: 'うらやましい、憧れる', category: 'emotion_psychology' },
  { id: 'w172', hanzi: '嫉妒', pinyin: 'jí dù', meaning: 'jealousy, to be jealous', meaningJa: '嫉妬する', category: 'emotion_psychology' },
  { id: 'w173', hanzi: '尴尬', pinyin: 'gān gà', meaning: 'awkward, embarrassing', meaningJa: '気まずい、バツが悪い', category: 'emotion_psychology' },
  { id: 'w174', hanzi: '沮丧', pinyin: 'jǔ sàng', meaning: 'dejected, frustrated', meaningJa: 'がっくりした、意気消沈', category: 'emotion_psychology' },
  { id: 'w175', hanzi: '愤怒', pinyin: 'fèn nù', meaning: 'angry, fury', meaningJa: '憤怒、怒り', category: 'emotion_psychology' },
  { id: 'w176', hanzi: '平静', pinyin: 'píng jìng', meaning: 'calm, serene', meaningJa: '平静な、落ち着いた', category: 'emotion_psychology' },
  { id: 'w177', hanzi: '害羞', pinyin: 'hài xiū', meaning: 'shy, bashful', meaningJa: '恥ずかしがり屋', category: 'emotion_psychology' },
  { id: 'w178', hanzi: '感动', pinyin: 'gǎn dòng', meaning: 'moved, touched emotionally', meaningJa: '感動する', category: 'emotion_psychology' },
  { id: 'w179', hanzi: '珍惜', pinyin: 'zhēn xī', meaning: 'to cherish, treasure', meaningJa: '大切にする、珍重する', category: 'emotion_psychology' },
  { id: 'w180', hanzi: '紧张', pinyin: 'jǐn zhāng', meaning: 'nervous, tense', meaningJa: '緊張した', category: 'emotion_psychology' },

  // ── places_geography ───────────────────────────────────────────────────
  { id: 'w181', hanzi: '景区', pinyin: 'jǐng qū', meaning: 'scenic area, tourist area', meaningJa: '景勝地、観光区域', category: 'places_geography', isPlaceRelated: true },
  { id: 'w182', hanzi: '首都', pinyin: 'shǒu dū', meaning: 'capital city', meaningJa: '首都', category: 'places_geography', isPlaceRelated: true },
  { id: 'w183', hanzi: '边境', pinyin: 'biān jìng', meaning: 'border, frontier', meaningJa: '国境、辺境', category: 'places_geography', isPlaceRelated: true },
  { id: 'w184', hanzi: '地标', pinyin: 'dì biāo', meaning: 'landmark', meaningJa: 'ランドマーク', category: 'places_geography', isPlaceRelated: true },
  { id: 'w185', hanzi: '广场', pinyin: 'guǎng chǎng', meaning: 'square, plaza', meaningJa: '広場', category: 'places_geography', isPlaceRelated: true },
  { id: 'w186', hanzi: '郊区', pinyin: 'jiāo qū', meaning: 'suburbs, outskirts', meaningJa: '郊外', category: 'places_geography', isPlaceRelated: true },
  { id: 'w187', hanzi: '古迹', pinyin: 'gǔ jì', meaning: 'historic site, antiquity', meaningJa: '史跡、旧跡', category: 'places_geography', isPlaceRelated: true },
  { id: 'w188', hanzi: '地区', pinyin: 'dì qū', meaning: 'region, area, district', meaningJa: '地区、地域', category: 'places_geography', isPlaceRelated: true },
  { id: 'w189', hanzi: '乡村', pinyin: 'xiāng cūn', meaning: 'rural area, countryside', meaningJa: '農村、田舎', category: 'places_geography', isPlaceRelated: true },
  { id: 'w190', hanzi: '街道', pinyin: 'jiē dào', meaning: 'street, neighborhood', meaningJa: '通り、街道', category: 'places_geography', isPlaceRelated: true },
  { id: 'w191', hanzi: '村庄', pinyin: 'cūn zhuāng', meaning: 'village', meaningJa: '村', category: 'places_geography', isPlaceRelated: true },
  { id: 'w192', hanzi: '小镇', pinyin: 'xiǎo zhèn', meaning: 'small town', meaningJa: '小さな町', category: 'places_geography', isPlaceRelated: true },
  { id: 'w193', hanzi: '港口', pinyin: 'gǎng kǒu', meaning: 'port, harbor', meaningJa: '港', category: 'places_geography', isPlaceRelated: true },
  { id: 'w194', hanzi: '半岛', pinyin: 'bàn dǎo', meaning: 'peninsula', meaningJa: '半島', category: 'places_geography', isPlaceRelated: true },
  { id: 'w195', hanzi: '沿海', pinyin: 'yán hǎi', meaning: 'coastal, along the coast', meaningJa: '沿海、海沿い', category: 'places_geography', isPlaceRelated: true },
  { id: 'w196', hanzi: '山脉', pinyin: 'shān mài', meaning: 'mountain range', meaningJa: '山脈', category: 'places_geography', isPlaceRelated: true },
  { id: 'w197', hanzi: '平原', pinyin: 'píng yuán', meaning: 'plain, flatland', meaningJa: '平原', category: 'places_geography', isPlaceRelated: true },
  { id: 'w198', hanzi: '名胜', pinyin: 'míng shèng', meaning: 'famous scenic spot', meaningJa: '名勝', category: 'places_geography', isPlaceRelated: true },
  { id: 'w199', hanzi: '遗址', pinyin: 'yí zhǐ', meaning: 'ruins, historical site', meaningJa: '遺跡', category: 'places_geography', isPlaceRelated: true },
  { id: 'w200', hanzi: '海拔', pinyin: 'hǎi bá', meaning: 'altitude, elevation', meaningJa: '海抜、標高', category: 'places_geography', isPlaceRelated: true },
  { id: 'w201', hanzi: '景观', pinyin: 'jǐng guān', meaning: 'landscape, scenery', meaningJa: '景観', category: 'places_geography', isPlaceRelated: true },
  { id: 'w202', hanzi: '旅游', pinyin: 'lǚ yóu', meaning: 'tourism, to travel', meaningJa: '旅行する、観光', category: 'places_geography', isPlaceRelated: true },

  // ── nature_environment ─────────────────────────────────────────────────
  { id: 'w203', hanzi: '生态', pinyin: 'shēng tài', meaning: 'ecology, ecosystem', meaningJa: '生態系', category: 'nature_environment' },
  { id: 'w204', hanzi: '资源', pinyin: 'zī yuán', meaning: 'resources', meaningJa: '資源', category: 'nature_environment' },
  { id: 'w205', hanzi: '污染', pinyin: 'wū rǎn', meaning: 'pollution, to pollute', meaningJa: '汚染', category: 'nature_environment' },
  { id: 'w206', hanzi: '气候', pinyin: 'qì hòu', meaning: 'climate', meaningJa: '気候', category: 'nature_environment' },
  { id: 'w207', hanzi: '保护', pinyin: 'bǎo hù', meaning: 'to protect, protection', meaningJa: '保護する', category: 'nature_environment' },
  { id: 'w208', hanzi: '能源', pinyin: 'néng yuán', meaning: 'energy resources', meaningJa: 'エネルギー資源', category: 'nature_environment' },
  { id: 'w209', hanzi: '森林', pinyin: 'sēn lín', meaning: 'forest', meaningJa: '森林', category: 'nature_environment', isPlaceRelated: true },
  { id: 'w210', hanzi: '环保', pinyin: 'huán bǎo', meaning: 'environmental protection', meaningJa: '環境保護', category: 'nature_environment' },
  { id: 'w211', hanzi: '野生', pinyin: 'yě shēng', meaning: 'wild, wildlife', meaningJa: '野生の', category: 'nature_environment' },
  { id: 'w212', hanzi: '物种', pinyin: 'wù zhǒng', meaning: 'species', meaningJa: '種、生物種', category: 'nature_environment' },
  { id: 'w213', hanzi: '灭绝', pinyin: 'miè jué', meaning: 'extinct, extinction', meaningJa: '絶滅する', category: 'nature_environment' },
  { id: 'w214', hanzi: '气象', pinyin: 'qì xiàng', meaning: 'meteorology, weather', meaningJa: '気象', category: 'nature_environment' },
  { id: 'w215', hanzi: '洪水', pinyin: 'hóng shuǐ', meaning: 'flood', meaningJa: '洪水', category: 'nature_environment' },
  { id: 'w216', hanzi: '干旱', pinyin: 'gān hàn', meaning: 'drought', meaningJa: '干ばつ', category: 'nature_environment' },
  { id: 'w217', hanzi: '地震', pinyin: 'dì zhèn', meaning: 'earthquake', meaningJa: '地震', category: 'nature_environment' },
  { id: 'w218', hanzi: '海洋', pinyin: 'hǎi yáng', meaning: 'ocean, sea', meaningJa: '海洋', category: 'nature_environment', isPlaceRelated: true },
  { id: 'w219', hanzi: '沙漠', pinyin: 'shā mò', meaning: 'desert', meaningJa: '砂漠', category: 'nature_environment', isPlaceRelated: true },
  { id: 'w220', hanzi: '湿地', pinyin: 'shī dì', meaning: 'wetland, marsh', meaningJa: '湿地', category: 'nature_environment', isPlaceRelated: true },
  { id: 'w221', hanzi: '空气', pinyin: 'kōng qì', meaning: 'air', meaningJa: '空気', category: 'nature_environment' },
  { id: 'w222', hanzi: '可持续', pinyin: 'kě chí xù', meaning: 'sustainable', meaningJa: '持続可能な', category: 'nature_environment' },
  { id: 'w223', hanzi: '碳排放', pinyin: 'tàn pái fàng', meaning: 'carbon emissions', meaningJa: '炭素排出', category: 'nature_environment' },

  // ── food_drink ─────────────────────────────────────────────────────────
  { id: 'w224', hanzi: '食材', pinyin: 'shí cái', meaning: 'ingredients, food materials', meaningJa: '食材', category: 'food_drink' },
  { id: 'w225', hanzi: '口味', pinyin: 'kǒu wèi', meaning: 'taste, flavor', meaningJa: '味、口当たり', category: 'food_drink' },
  { id: 'w226', hanzi: '菜肴', pinyin: 'cài yáo', meaning: 'dish, cuisine', meaningJa: '料理、おかず', category: 'food_drink' },
  { id: 'w227', hanzi: '饮食', pinyin: 'yǐn shí', meaning: 'diet, food and drink', meaningJa: '飲食、食生活', category: 'food_drink' },
  { id: 'w228', hanzi: '烹饪', pinyin: 'pēng rèn', meaning: 'cooking, culinary arts', meaningJa: '料理、調理', category: 'food_drink' },
  { id: 'w229', hanzi: '特色', pinyin: 'tè sè', meaning: 'characteristic, special feature', meaningJa: '特色、特徴', category: 'food_drink' },
  { id: 'w230', hanzi: '美食', pinyin: 'měi shí', meaning: 'delicacy, gourmet food', meaningJa: 'グルメ、美食', category: 'food_drink' },
  { id: 'w231', hanzi: '火锅', pinyin: 'huǒ guō', meaning: 'hotpot', meaningJa: '火鍋', category: 'food_drink' },
  { id: 'w232', hanzi: '调料', pinyin: 'tiáo liào', meaning: 'seasoning, condiment', meaningJa: '調味料', category: 'food_drink' },
  { id: 'w233', hanzi: '饮料', pinyin: 'yǐn liào', meaning: 'beverage, drink', meaningJa: '飲み物', category: 'food_drink' },
  { id: 'w234', hanzi: '零食', pinyin: 'líng shí', meaning: 'snack, nibbles', meaningJa: 'おやつ、スナック', category: 'food_drink' },
  { id: 'w235', hanzi: '素食', pinyin: 'sù shí', meaning: 'vegetarian food', meaningJa: 'ベジタリアン料理', category: 'food_drink' },
  { id: 'w236', hanzi: '甜点', pinyin: 'tián diǎn', meaning: 'dessert, sweet', meaningJa: 'デザート', category: 'food_drink' },
  { id: 'w237', hanzi: '外卖', pinyin: 'wài mài', meaning: 'takeaway, food delivery', meaningJa: 'テイクアウト、デリバリー', category: 'food_drink' },
  { id: 'w238', hanzi: '预订', pinyin: 'yù dìng', meaning: 'to reserve, book', meaningJa: '予約する', category: 'food_drink' },
  { id: 'w239', hanzi: '分量', pinyin: 'fèn liàng', meaning: 'portion, serving size', meaningJa: '量、一人前', category: 'food_drink' },
  { id: 'w240', hanzi: '新鲜', pinyin: 'xīn xiān', meaning: 'fresh', meaningJa: '新鮮な', category: 'food_drink' },
  { id: 'w241', hanzi: '卫生', pinyin: 'wèi shēng', meaning: 'hygiene, sanitation', meaningJa: '衛生', category: 'food_drink' },

  // ── technology ─────────────────────────────────────────────────────────
  { id: 'w242', hanzi: '网络', pinyin: 'wǎng luò', meaning: 'network, internet', meaningJa: 'ネットワーク、インターネット', category: 'technology' },
  { id: 'w243', hanzi: '软件', pinyin: 'ruǎn jiàn', meaning: 'software', meaningJa: 'ソフトウェア', category: 'technology' },
  { id: 'w244', hanzi: '数据', pinyin: 'shù jù', meaning: 'data', meaningJa: 'データ', category: 'technology' },
  { id: 'w245', hanzi: '人工智能', pinyin: 'rén gōng zhì néng', meaning: 'artificial intelligence', meaningJa: '人工知能、AI', category: 'technology' },
  { id: 'w246', hanzi: '平台', pinyin: 'píng tái', meaning: 'platform', meaningJa: 'プラットフォーム', category: 'technology' },
  { id: 'w247', hanzi: '应用', pinyin: 'yìng yòng', meaning: 'application, app; to apply', meaningJa: 'アプリ；応用する', category: 'technology' },
  { id: 'w248', hanzi: '数字', pinyin: 'shù zì', meaning: 'digital; numeral', meaningJa: 'デジタル；数字', category: 'technology' },
  { id: 'w249', hanzi: '信息', pinyin: 'xìn xī', meaning: 'information, data', meaningJa: '情報', category: 'technology' },
  { id: 'w250', hanzi: '隐私', pinyin: 'yǐn sī', meaning: 'privacy', meaningJa: 'プライバシー', category: 'technology' },
  { id: 'w251', hanzi: '硬件', pinyin: 'yìng jiàn', meaning: 'hardware', meaningJa: 'ハードウェア', category: 'technology' },
  { id: 'w252', hanzi: '程序', pinyin: 'chéng xù', meaning: 'program, procedure', meaningJa: 'プログラム、手順', category: 'technology' },
  { id: 'w253', hanzi: '系统', pinyin: 'xì tǒng', meaning: 'system', meaningJa: 'システム', category: 'technology' },
  { id: 'w254', hanzi: '下载', pinyin: 'xià zài', meaning: 'to download', meaningJa: 'ダウンロードする', category: 'technology' },
  { id: 'w255', hanzi: '上传', pinyin: 'shàng chuán', meaning: 'to upload', meaningJa: 'アップロードする', category: 'technology' },
  { id: 'w256', hanzi: '搜索', pinyin: 'sōu suǒ', meaning: 'to search', meaningJa: '検索する', category: 'technology' },
  { id: 'w257', hanzi: '账号', pinyin: 'zhàng hào', meaning: 'account, username', meaningJa: 'アカウント', category: 'technology' },
  { id: 'w258', hanzi: '密码', pinyin: 'mì mǎ', meaning: 'password, cipher', meaningJa: 'パスワード', category: 'technology' },
  { id: 'w259', hanzi: '直播', pinyin: 'zhí bō', meaning: 'live streaming, live broadcast', meaningJa: 'ライブ配信', category: 'technology' },
  { id: 'w260', hanzi: '人脸识别', pinyin: 'rén liǎn shí bié', meaning: 'facial recognition', meaningJa: '顔認識', category: 'technology' },
  { id: 'w261', hanzi: '云计算', pinyin: 'yún jì suàn', meaning: 'cloud computing', meaningJa: 'クラウドコンピューティング', category: 'technology' },

  // ── transportation ─────────────────────────────────────────────────────
  { id: 'w262', hanzi: '交通', pinyin: 'jiāo tōng', meaning: 'traffic, transportation', meaningJa: '交通', category: 'transportation' },
  { id: 'w263', hanzi: '航班', pinyin: 'háng bān', meaning: 'flight, scheduled service', meaningJa: 'フライト、便', category: 'transportation' },
  { id: 'w264', hanzi: '签证', pinyin: 'qiān zhèng', meaning: 'visa', meaningJa: 'ビザ', category: 'transportation' },
  { id: 'w265', hanzi: '护照', pinyin: 'hù zhào', meaning: 'passport', meaningJa: 'パスポート', category: 'transportation' },
  { id: 'w266', hanzi: '行李', pinyin: 'xíng li', meaning: 'luggage, baggage', meaningJa: '荷物、バゲージ', category: 'transportation' },
  { id: 'w267', hanzi: '出发', pinyin: 'chū fā', meaning: 'to depart, set off', meaningJa: '出発する', category: 'transportation' },
  { id: 'w268', hanzi: '抵达', pinyin: 'dǐ dá', meaning: 'to arrive', meaningJa: '到着する', category: 'transportation' },
  { id: 'w269', hanzi: '转机', pinyin: 'zhuǎn jī', meaning: 'to transfer (flights)', meaningJa: 'トランジットする', category: 'transportation' },
  { id: 'w270', hanzi: '铁路', pinyin: 'tiě lù', meaning: 'railway, railroad', meaningJa: '鉄道', category: 'transportation' },
  { id: 'w271', hanzi: '高铁', pinyin: 'gāo tiě', meaning: 'high-speed rail', meaningJa: '高速鉄道', category: 'transportation' },
  { id: 'w272', hanzi: '地铁', pinyin: 'dì tiě', meaning: 'subway, metro', meaningJa: '地下鉄', category: 'transportation' },
  { id: 'w273', hanzi: '公路', pinyin: 'gōng lù', meaning: 'highway, road', meaningJa: '公道、幹線道路', category: 'transportation' },
  { id: 'w274', hanzi: '堵车', pinyin: 'dǔ chē', meaning: 'traffic jam', meaningJa: '渋滞', category: 'transportation' },
  { id: 'w275', hanzi: '停车', pinyin: 'tíng chē', meaning: 'to park, parking', meaningJa: '駐車する', category: 'transportation' },
  { id: 'w276', hanzi: '导航', pinyin: 'dǎo háng', meaning: 'navigation', meaningJa: 'ナビゲーション', category: 'transportation' },
  { id: 'w277', hanzi: '驾驶', pinyin: 'jià shǐ', meaning: 'to drive, operate a vehicle', meaningJa: '運転する', category: 'transportation' },
  { id: 'w278', hanzi: '候机', pinyin: 'hòu jī', meaning: 'to wait for a flight', meaningJa: '搭乗を待つ', category: 'transportation' },
  { id: 'w279', hanzi: '检票', pinyin: 'jiǎn piào', meaning: 'ticket inspection', meaningJa: '改札、検票', category: 'transportation' },
  { id: 'w280', hanzi: '安检', pinyin: 'ān jiǎn', meaning: 'security check', meaningJa: 'セキュリティチェック', category: 'transportation' },
  { id: 'w281', hanzi: '海关', pinyin: 'hǎi guān', meaning: 'customs', meaningJa: '税関', category: 'transportation' },
]

export const WORD_CATEGORIES: Record<
  WordCategory,
  { label: string; labelZh: string; color: string; bgColor: string; emoji: string }
> = {
  daily_life:         { label: '日常生活',       labelZh: '日常生活', color: 'text-blue-700',    bgColor: 'bg-blue-50 border-blue-200',      emoji: '🏠' },
  work_business:      { label: '仕事・ビジネス',   labelZh: '商务工作', color: 'text-orange-700',  bgColor: 'bg-orange-50 border-orange-200',    emoji: '💼' },
  education:          { label: '教育・学習',      labelZh: '教育学习', color: 'text-indigo-700',  bgColor: 'bg-indigo-50 border-indigo-200',    emoji: '📚' },
  culture_art:        { label: '文化・芸術',      labelZh: '文化艺术', color: 'text-pink-700',    bgColor: 'bg-pink-50 border-pink-200',        emoji: '🎨' },
  society_politics:   { label: '社会・政治',      labelZh: '社会政治', color: 'text-gray-700',    bgColor: 'bg-gray-50 border-gray-200',        emoji: '🏛️' },
  health_body:        { label: '健康・身体',      labelZh: '健康身体', color: 'text-green-700',   bgColor: 'bg-green-50 border-green-200',      emoji: '💪' },
  emotion_psychology: { label: '感情・心理',      labelZh: '情感心理', color: 'text-purple-700',  bgColor: 'bg-purple-50 border-purple-200',    emoji: '💭' },
  places_geography:   { label: '場所・地理',      labelZh: '地理场所', color: 'text-teal-700',    bgColor: 'bg-teal-50 border-teal-200',        emoji: '🗺️' },
  nature_environment: { label: '自然・環境',      labelZh: '自然环境', color: 'text-emerald-700', bgColor: 'bg-emerald-50 border-emerald-200',  emoji: '🌿' },
  food_drink:         { label: '食・飲み物',      labelZh: '饮食美食', color: 'text-yellow-700',  bgColor: 'bg-yellow-50 border-yellow-200',    emoji: '🍜' },
  technology:         { label: 'テクノロジー',    labelZh: '科技数字', color: 'text-cyan-700',    bgColor: 'bg-cyan-50 border-cyan-200',        emoji: '💻' },
  transportation:     { label: '交通・移動',      labelZh: '交通出行', color: 'text-rose-700',    bgColor: 'bg-rose-50 border-rose-200',        emoji: '✈️' },
}

export function getPlatformLinks(word: ChineseWord) {
  const encoded = encodeURIComponent(word.hanzi)
  return {
    xiaohongshu: `https://www.xiaohongshu.com/search_result?keyword=${encoded}&type=51`,
    baiduDict: `https://dict.baidu.com/s?wd=${encoded}`,
    baiduMap: word.isPlaceRelated ? `https://map.baidu.com/search/${encoded}/` : null,
  }
}
